data:
    init_args:
        name: WHITE_06
catalog:
    Mcut: 0.6
    path: ../../Datasets/SCEDC/SCEDC_catalog.csv
    path_to_polygon: ../../Datasets/SCEDC/SCEDC_shape.npy
    auxiliary_start: 2008-01-01 00:00:00
    train_nll_start: 2009-01-01 00:00:00
    val_nll_start: 2014-01-01 00:00:00
    test_nll_start: 2017-01-01 00:00:00
    test_nll_end: 2021-01-01 00:00:00
